MODEL:
  STYLE_ENCODER_LAYERS: 3
  NUM_IMGS: 12
  IN_CHANNELS: 4
  OUT_CHANNELS: 4
  NUM_RES_BLOCKS: 1
  NUM_HEADS: 4
  EMB_DIM: 512
SOLVER:
  BASE_LR: 0.0001
  EPOCHS: 1000
  WARMUP_ITERS: 25000
  TYPE: AdamW
  GRAD_L2_CLIP: 5.0
TRAIN:
  TYPE: train
  IMS_PER_BATCH: 8
  SNAPSHOT_BEGIN: 1
  SNAPSHOT_ITERS: 20
  VALIDATE_BEGIN: 0
  VALIDATE_ITERS: 1
  SEED: 1001
  IMG_H: 64
  IMG_W: 1024
TEST:
  TYPE: val
  IMS_PER_BATCH: 4
  IMG_H: 64
  IMG_W: 1024
DATA_LOADER:
  NUM_THREADS: 8
  IAMGE_PATH: /storage/1/saima/oneDM/upti2_processed
  STYLE_PATH: /storage/1/saima/oneDM/upti2_processed
  LAPLACE_PATH: /storage/1/saima/oneDM/upti2_processed_laplace
OUTPUT_DIR: /storage/1/saima/oneDM/output_upti2_sentences
