MODEL:
  STYLE_ENCODER_LAYERS: 3
  NUM_IMGS: 15
  IN_CHANNELS: 4
  OUT_CHANNELS: 4
  NUM_RES_BLOCKS: 1
  NUM_HEADS: 4
  EMB_DIM: 512
SOLVER:
  BASE_LR: 0.0001
  EPOCHS: 200
  WARMUP_ITERS: 15000
  TYPE: AdamW
  GRAD_L2_CLIP: 5.0
TRAIN:
  TYPE: train
  IMS_PER_BATCH: 32
  SNAPSHOT_BEGIN: 1
  SNAPSHOT_ITERS: 25  # Save every 25 epochs (8 checkpoints total)
  VALIDATE_BEGIN: 1
  VALIDATE_ITERS: 625  # ~1 epoch (20000/32=625 steps per epoch)
  SEED: 1001
  IMG_H: 64
  IMG_W: 64
TEST:
  TYPE: val
  IMS_PER_BATCH: 32
  IMG_H: 64
  IMG_W: 64
DATA_LOADER:
  NUM_THREADS: 16
  IAMGE_PATH: /storage/1/saima/oneDM/upti2_processed
  STYLE_PATH: /storage/1/saima/oneDM/upti2_processed
  LAPLACE_PATH: /storage/1/saima/oneDM/upti2_processed_laplace
OUTPUT_DIR: /storage/1/saima/oneDM/output_upti2
